[project]
name = "curlit"
version = "0.1.0"
description = "Curl your HTTP!"
authors = [{ name = "Shiv Dhar", email = "shivdhar@gmail.com" }]
requires-python = ">=3.10,<4"
license = "MIT"
dependencies = ["pycurl>=7,<8"]

[dependency-groups]
dev = [
    "icecream>=2,<3",
    "pytest>=9.0.3,<10",
    "requests>=2,<3",
    "ruff>=0.15.7",
]

